micronaut:
  application:
    name: report-service
  server:
    port: 8082
kafka:
  bootstrap:
    servers: localhost:19092
mongodb:
  uri: mongodb://root:root@localhost:27017/sales-db?authSource=admin

consul:
  client:
    discovery:
      enabled: true
    default-zone: "localhost:8500"
